version: "3.2"
services:
  frontend:
    restart: always
    command : npm run dev
    container_name: front
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true